### ISSUE TITLE
cannot import name 'KnowledgeBase' from partially initialized module 'cytopus'

### ISSUE THREAD

**Issue by GabyBG** [wallet-maker/cytopus#6]
hello,

I am trying to use cytopus (in order to use Spectra) but I am running with issues since trying to import the module.I am currently working on an EC2 instance, Ubuntu 22.04.1 LTS (GNU/Linux 6.2.0-1012-aws x86_64)

I ran:
```
import cytopus as cp
```

but I got the following error:
```
ITraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/scFates-gpu/lib/python3.8/site-packages/cytopus/__init__.py", line 3, in <module>
    from . import KnowledgeBase as kb
ImportError: cannot import name 'KnowledgeBase' from partially initialized module 'cytopus' (most likely due to a circular import) (/home/ubuntu/anaconda3/envs/scFates-gpu/lib/python3.8/site-packages/cytopus/__init__.py)
```

I am wondering if I missed a critical step, but seems like the package and some dependencies were installed correctly. 

Thank you for your help

**Comment by wallet-maker** [comment]
Hi thanks for using Cytopus&Spectra :) . 

I'll look into this. Did you install cytopus from source or from pip ? 

Thanks,
Thomas

**Comment by GabyBG** [comment]
I used pip install 


> Hi thanks for using Cytopus&Spectra :) .
> 
> I'll look into this. Did you install cytopus from source or from pip ?
> 
> Thanks, Thomas

**Comment by wallet-maker** [comment]
ughhh you're totally right. I fear this is a problem of the version we pushed to pip. 

Can you try install from source, it should be fine then:

[](pip install git+https://github.com/wallet-maker/cytopus.git)

We'll fix the version on pip asap

Thanks,
Thomas

**Comment by GabyBG** [comment]
I can load the package when I install from source.

Thanks

**Comment by Tobiaspk** [comment]
Cytopus version 1.3.2 now fixes the import issues. It's available on pip. 👍 

Thanks for reporting this issue.
